In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
df=pd.read_csv("netflix_db.csv",lineterminator='\n')

In [23]:
df.head(1)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...

In [25]:
cols=['Original_Language','Poster_Url','Overview']

In [27]:

df.drop(cols,axis=1,inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2447 entries, 0 to 2446
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  2447 non-null   object
 1   Title         2447 non-null   object
 2   Popularity    2447 non-null   float64
 3   Vote_Count    2447 non-null   int64
 4   Vote_Average  2447 non-null   float64
 5   Genre         2447 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 114.8+ KB

In [31]:
# output_path = "updated_data.csv"
# data.to_csv(output_path, index=False)

# print("Dataset processed and saved successfully as:", output_path)

In [33]:
# df=pd.read_csv("updated_data.csv", lineterminator='\n')

In [35]:
# df.head()

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2447 entries, 0 to 2446
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  2447 non-null   object
 1   Title         2447 non-null   object
 2   Popularity    2447 non-null   float64
 3   Vote_Count    2447 non-null   int64
 4   Vote_Average  2447 non-null   float64
 5   Genre         2447 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 114.8+ KB

In [39]:
df['Release_Date']=pd.to_datetime(df['Release_Date'])

In [41]:
print(df['Release_Date'].dtypes)

datetime64[ns]

In [43]:
df['Release_Date']=df['Release_Date'].dt.year

In [45]:
df['Release_Date'].head()

0    2021
1    2022
2    2022
3    2021
4    2021
Name: Release_Date, dtype: int64

In [47]:
print(df['Release_Date'].dtypes)

int64

In [49]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,6.3,Thriller
3,2021,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"

In [51]:

df.columns

Index(['Release_Date', 'Title', 'Popularity', 'Vote_Count', 'Vote_Average',
       'Genre'],
      dtype='object')

In [53]:
def categorizelabels(df,col,labels):
    edges=[df[col].describe()['min'],
          df[col].describe()['25%'],
          df[col].describe()['50%'],
          df[col].describe()['75%'],
          df[col].describe()['max']]
    df[col]=pd.cut(df[col],edges,labels=labels,duplicates='drop')
    return df

In [55]:
labels=['not_popular','below_average','average','popular']

categorizelabels(df,'Vote_Average',labels)
df['Vote_Average'].unique()

['popular', 'below_average', 'average', 'not_popular', NaN]
Categories (4, object): ['not_popular' < 'below_average' < 'average' < 'popular']

In [57]:
df.head(2)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,popular,"Crime, Mystery, Thriller"

In [59]:
df['Vote_Average'].value_counts()

not_popular      622
below_average    621
average          601
popular          581
Name: Vote_Average, dtype: int64

In [61]:
df.isna().sum()

Release_Date     0
Title            0
Popularity       0
Vote_Count       0
Vote_Average    22
Genre            0
dtype: int64

In [63]:
df['Vote_Average'].isnull().value_counts()

False    2425
True       22
Name: Vote_Average, dtype: int64

In [65]:
df.dropna(inplace=True)

In [67]:
df['Vote_Average'].isnull().value_counts()

False    2425
Name: Vote_Average, dtype: int64

In [69]:
df.isna().sum()

Release_Date    0
Title           0
Popularity      0
Vote_Count      0
Vote_Average    0
Genre           0
dtype: int64

# we will split the genre into a list and then explode our dataframe to haveone genre per row for each movie

In [72]:
df['Genre']=df['Genre'].str.split(', ')

In [74]:
df=df.explode('Genre').reset_index(drop=True)

In [76]:
df.head(2)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,popular,Adventure

# casting column into category

In [79]:
df['Genre']=df['Genre'].astype('category')
df['Genre'].dtypes

CategoricalDtype(categories=['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
                  'Documentary', 'Drama', 'Family', 'Fantasy', 'History',
                  'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
                  'TV Movie', 'Thriller', 'War', 'Western'],
, ordered=False)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6713 entries, 0 to 6712
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  6713 non-null   int64
 1   Title         6713 non-null   object
 2   Popularity    6713 non-null   float64
 3   Vote_Count    6713 non-null   int64
 4   Vote_Average  6713 non-null   category
 5   Genre         6713 non-null   category
dtypes: category(2), float64(1), int64(2), object(1)
memory usage: 223.9+ KB

In [83]:
df.nunique()

Release_Date      74
Title           2378
Popularity      2379
Vote_Count      1835
Vote_Average       4
Genre             19
dtype: int64