In [63]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
df=pd.read_csv("netflix_db.csv",lineterminator='\n')

In [67]:
df.head(1)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...

In [69]:
cols=['Original_Language','Poster_Url','Overview']

In [71]:
df.drop(cols,axis=1)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...
2442,2004-04-13,13 Going on 30,35.313,4165,6.7,"Comedy, Fantasy, Romance"
2443,2005-06-29,Fantastic Four,35.313,7911,5.8,"Action, Adventure, Fantasy, Science Fiction"
2444,2020-10-29,A Gruta,35.280,65,6.4,Horror
2445,1994-07-01,Baby's Day Out,35.276,996,6.2,"Family, Comedy, Adventure, Crime"
2446,1991-11-21,An American Tail: Fievel Goes West,35.266,588,6.3,"Adventure, Animation, Family, Western"

In [73]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  2447.000000   2447.000000   2447.000000
mean    101.913947   3146.480180      6.625868
std     206.080884   4313.779159      1.102282
min      35.266000      0.000000      0.000000
25%      43.347500    227.000000      6.100000
50%      57.705000   1298.000000      6.700000
75%      92.618000   4559.000000      7.300000
max    5083.954000  31077.000000      9.100000

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2447 entries, 0 to 2446
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       2447 non-null   object
 1   Title              2447 non-null   object
 2   Overview           2447 non-null   object
 3   Popularity         2447 non-null   float64
 4   Vote_Count         2447 non-null   int64
 5   Vote_Average       2447 non-null   float64
 6   Original_Language  2447 non-null   object
 7   Genre              2447 non-null   object
 8   Poster_Url         2447 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 172.2+ KB

In [77]:
df['Release_Date']=pd.to_datetime(df['Release_Date'])

In [79]:
print(df['Release_Date'].dtypes)

datetime64[ns]

In [81]:
df['Release_Date']=df['Release_Date'].dt.year

In [83]:
df['Release_Date'].head()

0    2021
1    2022
2    2022
3    2021
4    2021
Name: Release_Date, dtype: int64

In [85]:
print(df['Release_Date'].dtypes)

int64

In [87]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [89]:

df.columns

Index(['Release_Date', 'Title', 'Overview', 'Popularity', 'Vote_Count',
       'Vote_Average', 'Original_Language', 'Genre', 'Poster_Url'],
      dtype='object')

In [91]:
def categorizelabels(df,col,labels):
    edges=[df[col].describe()['min'],
          df[col].describe()['25%'],
          df[col].describe()['50%'],
          df[col].describe()['75%'],
          df[col].describe()['max']]
    df[col]=pd.cut(df[col],edges,labels=labels,duplicates='drop')
    return df

In [93]:
labels=['not_popular','below_average','average','popular']

categorizelabels(df,'Vote_Average',labels)
df['Vote_Average'].unique()

['popular', 'below_average', 'average', 'not_popular', NaN]
Categories (4, object): ['not_popular' < 'below_average' < 'average' < 'popular']

In [97]:
df.head(2)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,popular,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,popular,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...

In [99]:
df['Vote_Average'].value_counts()

not_popular      622
below_average    621
average          601
popular          581
Name: Vote_Average, dtype: int64